### ISSUE TITLE
GIMP 2.10.0 Released

### ISSUE THREAD

**Issue by pixelr0** [snapcrafters/gimp#16] opened 2018-04-27 14:57 UTC
no joke
https://www.gimp.org/news/2018/04/27/gimp-2-10-0-released/

**Comment by omkarnathsingh** [comment] 2018-04-28 06:36
Please update to Gimp 2.10. Its stable now.

**Comment by diddledan** [comment] 2018-04-28 13:39
Yes, we're well aware that 2.10 is out. We can't get it released as a snap right now because of technical issues.

**Comment by pieqq** [comment] 2018-04-30 02:36
@diddledan, dare to share more info on what those technical issues are?

**Comment by etrigan63** [comment] 2018-04-30 04:01
Yes, please enlighten us!

**Comment by etrigan63** [comment] 2018-04-30 05:10
Posting a status on Twitter is like sending a message by opening your front door and shouting.

**Comment by omkarnathsingh** [comment] 2018-04-30 05:54
The dev didn't give snap update for earlier release also, I doubt we will get it.

**Comment by Ads20000** [comment] 2018-04-30 10:11
> Posting a status on Twitter is like sending a message by opening your front door and shouting.
It's the way that he has given us the info over what technical issues he's having, deal with it :P 

> The dev didn't give snap update for earlier release also, I doubt we will get it.
Which release are you referring to? 2.9.x were development releases and it was decided not to publish them to the snap store. The snap is currently on 2.8.22 which is the latest release in the 2.8 series, so he did produce that one eventually. It just can take some time to resolve technical issues :)

Also note that using your distribution's package is [the recommended way to get GIMP](https://www.gimp.org/downloads/) and, in Ubuntu 18.04, for example, it's often 2.8.22. If you're desperate to have 2.10 _right now_ then I have no problems with you getting the Flatpak instead. If on Ubuntu, for example, click [here](apt://gnome-software-plugin-flatpak) for `gnome-software-plugin-flatpak` and then [here](https://flathub.org/repo/appstream/org.gimp.GIMP.flatpakref) for the Flatpak. Then run `snap remove gimp` to just have the Flatpak version on your OS. You could return to the snap later, if you so wish, with `flatpak remove org.gimp.GIMP ; snap install gimp`.

**Comment by diddledan** [comment] 2018-04-30 19:45
> @diddledan, dare to share more info on what those technical issues are?

Sure, though I'm not sure that it'll help. It's not buildable, so if you are a `snapcraft` developer that can diagnose the build utility, then have at it and fix it for me. https://bugs.launchpad.net/snapcraft/+bug/1767625

> The dev didn't give snap update for earlier release also, I doubt we will get it.

I do this in my spare time. Entitled attitudes like this are toxic to the community, and cause people to get disillusioned and stop offering their services gratis. That does nobody any good. I didn't release previous 2.9.* builds because they didn't work. period. Would you rather I released it and caused you to have a completely non-functional installation, or wait until it actually does something?!

**Comment by diddledan** [comment] 2018-04-30 19:54
Please take note that I haven't been slacking in any way. I have been working on this cornerstone application for over 6 months to get you a working 2.9.* and subsequently 2.10.* build. They don't work yet, or cannot be built, so you haven't got them. In those past 6 months I have often spent several hours a day amounting to well over 100 hours total before I lost count. I envisage that once this final bug is squashed in snapcraft I'll be able to deliver the fruits of all that labour.

**Comment by etrigan63** [comment] 2018-04-30 19:57
I do realize that all of the volunteer work that goes into these things is horribly under-appreciated and for that I thank you for your efforts. 

Unfortunately, not communicating doesn't help much either. I know this from 30+ years as a developer. I personally don't use Twitter as it is a vapid popularity contest 24/7/365 and all meaningful information is lost in a monstrously large river of stupidities. YMMV, but that is how it presents itself to me. At least here on github, the information can more easily discovered. 

Thanks for the update, regardless. I will be using the flatpak in the meantime until this gets sorted out. Best of luck, and I hope the snapcraft developer is paying attention as this is a major release that they are missing out on.

**Comment by omkarnathsingh** [comment] 2018-05-01 03:06
@Ads20000 Snap do have edge and beta tracking channels, 2.9 could have been published there. Its the user responsibility if he uses beta/edge and its not running properly. Meanwhile stable could had been maintained where it is now. No issues with it.

**Comment by Ads20000** [comment] 2018-05-01 12:09
@omkarnathsingh Iirc Daniel explicitly rejected the possibility of pushing 2.9 to edge/beta, can't remember why, maybe because he never got 2.9 working? As usual, PRs accepted for the snapcraft bug if you know how to fix it!

**Comment by diddledan** [comment] 2018-05-01 13:36
For reference: https://github.com/snapcrafters/gimp/issues/4#issuecomment-352423462

**Comment by omkarnathsingh** [comment] 2018-05-02 08:51
I searched the build logs for error message and found out a/c to a stackoverflow solution to use stage for the common files.

```
stage:
    - usr/share/alsa/alsa.conf
    - usr/share/alsa/cards/USB-Audio.conf
    - usr/share/alsa/cards/aliases.conf
    - usr/share/alsa/pcm/dmix.conf
    - usr/share/alsa/pcm/dsnoop.conf
    - usr/share/alsa/pcm/surround21.conf
    - usr/share/alsa/pcm/surround40.conf
    - usr/share/alsa/pcm/surround41.conf
    - usr/share/alsa/pcm/surround50.conf
    - usr/share/alsa/pcm/surround51.conf
    - usr/share/alsa/pcm/surround71.conf```

Can we try it in part of gegl and try? 

(I am new to snap and its building, tried building and found out that I am lxc/lxd noob also)

**Comment by diddledan** [comment] 2018-05-02 12:34
I have no idea what you're talking about. GEGL builds fine.

**Comment by omkarnathsingh** [comment] 2018-05-02 17:46
Actually these are the files which are common to parts 'alsa-lib' and 'gegl'. So we need to use either for one of the part, so we need to stage it. Refer log here: https://build.snapcraft.io/user/snapcrafters/gimp/204597

```
make install DESTDIR=/build/gimp/parts/gegl/install
Failed to stage: Parts 'alsa-lib' and 'gegl' have the following files, but with different contents:
    usr/share/alsa/alsa.conf
    usr/share/alsa/cards/USB-Audio.conf
    usr/share/alsa/cards/aliases.conf
    usr/share/alsa/pcm/dmix.conf
    usr/share/alsa/pcm/dsnoop.conf
    usr/share/alsa/pcm/surround21.conf
    usr/share/alsa/pcm/surround40.conf
    usr/share/alsa/pcm/surround41.conf
    usr/share/alsa/pcm/surround50.conf
    usr/share/alsa/pcm/surround51.conf
    usr/share/alsa/pcm/surround71.conf

Snapcraft offers some capabilities to solve this by use of the following keywords:
    - `filesets`
    - `stage`
    - `snap`
    - `organize`

To learn more about these part keywords, run `snapcraft help plugins`.
Build failed
```

**Comment by popey** [comment] 2018-05-02 19:41
@omkarnathsingh thanks for the input, but we're on it. We know what the issue is, and it's a problem in the tools we're using to build the snap - snapcraft. The snapcraft developers are aware and are working on it.

**Comment by diddledan** [comment] 2018-05-08 12:04
We've just push a candidate snap to the store. Could you try running `sudo snap refresh --candidate gimp` if you have it installed, or `sudo snap install --candidate gimp` if you don't and try it out. Please report back your experiences.

**Comment by pixelr0** [comment] 2018-05-08 12:17
seems to work fine on ubuntu 16.04 but i get a LOT of warnings and critical messages in the console (pretty spammy)

```
Fontconfig error: failed reading config file
/snap/gimp/37/usr/bin/gimp: Gimp-Widgets-WARNING: parse_iso_codes: error parsing '/usr/share/xml/iso-codes/iso_639.xml': No such file or directory

Fontconfig error: failed reading config file

(gimp:21936): GLib-GIO-WARNING **: 15:09:13.705: Error creating IO channel for /proc/self/mountinfo: Permission denied (g-file-error-quark, 2)

(gimp:21936): GLib-GIO-CRITICAL **: 15:09:13.705: g_loadable_icon_load: assertion 'G_IS_LOADABLE_ICON (icon)' failed

(gimp:21936): Gtk-WARNING **: 15:09:13.705: Error loading theme icon 'edit-find' for stock: Failed to load icon

(gimp:21936): Gtk-CRITICAL **: 15:09:13.705: render_fallback_image: assertion 'pixbuf != NULL' failed

(gimp:21936): GLib-GObject-CRITICAL **: 15:09:13.705: g_object_ref: assertion 'G_IS_OBJECT (object)' failed

(gimp:21936): GLib-GIO-CRITICAL **: 15:09:13.706: g_loadable_icon_load: assertion 'G_IS_LOADABLE_ICON (icon)' failed

(gimp:21936): GLib-GIO-CRITICAL **: 15:09:13.709: g_loadable_icon_load: assertion 'G_IS_LOADABLE_ICON (icon)' failed

(gimp:21936): Gtk-WARNING **: 15:09:13.709: Error loading theme icon 'edit-find' for stock: Failed to load icon

(gimp:21936): Gtk-CRITICAL **: 15:09:13.709: render_fallback_image: assertion 'pixbuf != NULL' failed
```

**Comment by idzikovsky** [comment] 2018-05-11 16:50
Works fine, but I got no integration with Unity global menu on Ubuntu 16.04.

**Comment by pieqq** [comment] 2018-05-12 00:55
Thanks for this, @diddledan !

I installed it yesterday. When I try to print something, I can only print to a file. None of the printers around me are available, although they are properly configured and accessible in Ubuntu 18.04's `Printers` dialog.

I also have the same issue as reported by @idzikovsky regarding the missing icons in the text editor. (except I'm on 18.04, not 16.04)

**Comment by omkarnathsingh** [comment] 2018-05-12 02:27
Please update source code at https://github.com/snapcrafters/gimp/blob/master/snap/snapcraft.yaml 
Thanks.

**Comment by diddledan** [comment] 2018-05-13 17:29
@popey there's a PR to do just what @omkarnathsingh asked..

**Comment by diddledan** [comment] 2018-05-13 17:31
Can everyone who has a specific problem with GIMP 2.10.0 please file your bugs individually rather than aggregated under this issue. I'm closing this issue because 2.10.0 is now in the stable channel, albeit with bugs.

**Closed by diddledan** 2018-05-13 17:31 UTC
